### PR TITLE
Feature/download link for background

### PR DESCRIPTION
**Pull request by lukxxx**
#### Related issue
https://github.com/Lordhacker756/open-dashboard/issues/13
#### Changes
Fixed bug where background image was fetching with every interaction with app

### CODE REVIEW

**Comment by lukxxx** [comment]
@Lordhacker756 I dont know why are there conflicts but you know how to resolve them. :D

**Comment by lukxxx** [comment]
@Lordhacker756 Is this okay or is there something wrong?

**Comment by Lordhacker756** [comment]
Hey there @lukxxx , I tried to resolve the change and I saw another bug🐛. The fallback image is not loading when the network is not there and rather it's showing us a blank background. I've created a separate beta branch where we can test these problems

image

Please look into this bug and open a new pull request in the beta branch 😄

**Comment by lukxxx** [comment]
@Lordhacker756 okay thanks for the info I will look into this :D Thanks. Should be this pull request closed then or not?

**Comment by Lordhacker756** [comment]
I'm closing this pull request😄

**Pull request closed without merging**
