### PR TITLE
added button to download current background image

### PR DESCRIPTION
**Pull request by lukxxx**
#### Related issue 
https://github.com/Lordhacker756/open-dashboard/issues/13

#### Changes
Added download button to the right bottom corner to allow user to download current background.

#### Aditional info
When you look to additions and deletions there are so many of them. I am using PHPStorm IDE so maybe I reformat code so thats the reason. If you dont like it we can change it

### CODE REVIEW

**Comment by Lordhacker756** [comment]
Hey there @lukxxx, Thanks for the generous contribution. I looked at your code and your efforts are clearly visible however, the preview deployment is having an error. Opening the deployment is giving a blank page with the following error in the console

image

I took a look in the local storage to see that the app is not redirecting to the sign-up page(Hello) to get the name, place, and all the basic info before the main page is rendered.
image

Any idea how we can make this work😄

**Comment by lukxxx** [comment]
Hmm thats interesting I am looking into it.

**Comment by Lordhacker756** [comment]
Very well done @lukxxx 😄, Thanks for your generous contribution💖

**Comment by Lordhacker756** [comment]
@lukxxx, The code has a bug which I got to see after merging, It fetches the background image after every component toggle, like opening todo, Pomodoro, settings or personalize tab causes the background image to change

**Pull request merged**
